### ISSUE TITLE
Slicing disabled - currently printing or no model selected

### ISSUE THREAD

**Issue by b-morgan** [Garr-R/OctoPrint-Slicer#5]
I don't know how to fix `Slicing disabled - currently printing or no model selected`. Nothing is being printed (Virtual printer is connected) and I have uploaded and selected an .stl file.

![image](https://github.com/Garr-Garr/OctoPrint-InternalSlicer/assets/1547854/fb3187bd-5b04-403d-92ed-6015d0684647)

**Comment by Garr-Garr** [comment]
closing duplicate bug report ~ the issue is related to the LuzBot profile
